#!/bin/sh

# This is a script to bootstrap the build process in the halifax module
# and its submodules. Nothing complicated, but boring to do each time.


submodules=ghfaxviewer  # add gfax here...

for mod in $submodules; do
  echo Bootstrapping $mod...
  ( cd $mod && gettextize -c -f && aclocal -I macros && autoheader && \
    automake -a -c --gnu && autoconf );
done

echo Bootstrapping parent dir...
aclocal && automake -a -c --gnu && autoconf

echo done. Type configure now.
