#!/bin/sh

# This is a script to bootstrap the build process in the halifax modules.
# Nothing complicated, but boring to do each time.

gettextize -c -f
aclocal -I m4 --force
autoheader -f
automake -a -c --gnu
autoconf -f
echo You may now run 'configure'.
