.TH "ghfaxviewer" "1" "0.21.1" "Wolfgang Sourdeau" "The GNU HaliFAX Viewer"
.SH "NAME"
.LP 
ghfaxviewer \- display G3/G4 (fax) encoded TIFF files
.SH "SYNTAX"
.LP 
ghfaxviewer [\fIoptions\fP] <\fIfilename\fP>
.br 
ghfaxviewer

.SH "DESCRIPTION"
.LP 
This program is the GNU HaliFAX project's viewer. It is able to display fax files output by the \fIHylaFAX(tm)\fP system as well as any other G3/G4\-encoded TIFF fax file.
.LP 
The range of supported file\-formats will be extended in future versions.
.LP 
More informations about the GNU HaliFAX project are available at the GNU HaliFAX official website:
.LP 
\fBhttp://www.gnu.org/software/halifax/\fP
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "FILES"
.LP 
\fI~/.gconf/apps/ghfaxviewer/*\fP on the GNOME version
.br 
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBPRINTER\fP
Specifies the default printer.
.br 
If this variable isn't set, the system default printer will be used instead. The system default printer generally is the first entry specified in /etc/printcap.
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
ghfaxviewer
.LP 
Alternatively you can specify a filename on the command\-line:
.LP 
ghfaxviewer /var/spool/fax/recvq/fax00005.tif
.SH "AUTHORS"
.LP 
Wolfgang Sourdeau <wolfgang@gnu.org>
.SH "SEE ALSO"
.LP 
gfax(1)    \- the GNU HaliFAX Sender
.br 
viewfax(1)
